maazshakeel/devdynasty_project

- src/App.jsx
I've created the routing layout and also made 404 page in case if user go to wrong page they will see this 404 page not found.
> feat(route): add routing system & add 404 page not found

- index.html
- yarn.lock
Added some seo tags and changed the title of the website
Before:
After:
> fix: change title and seo tags

- src/components/AccordionAbout.jsx
- src/components/AccordionItem.jsx
- src/data/dataAccordion.js
- src/pages/Home.page.jsx
> feat(create a accordion in about section): added accordion in about section

- src/components/AccordionAbout.jsx
- src/components/AccordionItem.jsx
- src/components/Footer.jsx
- src/data/dataAccordion.js
- src/pages/Home.page.jsx
- tailwind.config.js
> Create a footer component #16

- src/pages/Home.page.jsx
> fix(homepage): resolve upside down welcome page and accordation

- src/components/AccordionAbout.jsx
- src/pages/Home.page.jsx
> fix(navbar and accordion): increase Navbar Z index to 50

- src/components/Footer.jsx
- src/pages/Home.page.jsx
> Footer component fix

- src/components/AccordionAbout.jsx
- src/components/AccordionItem.jsx
> style(accordion component): modify Accordion About Component

- src/App.jsx
- src/components/Footer.jsx
- src/components/Loader.jsx
- src/pages/Home.page.jsx
- tailwind.config.js
> feat(loader): add Loader for loading and use react lazy to optimize

- src/components/AccordionItem.jsx
- src/components/Slider.jsx
> fix(accessiblity): resolve accessiblity issue from lighthouse report

- src/components/Welcome.jsx
Optimized welcome page with clean coding
> fix(welcome.jsx): optimized a bit

- src/components/Loader.jsx
> fix(loader): center loader

- package.json
- src/components/Welcome.jsx
- yarn.lock
> Welcome optimization

- src/components/Province.jsx
> feat(province.jsx): add hover effect; expand;

- src/App.jsx
- src/components/Heading.jsx
- src/components/Province.jsx
- src/components/Slider.jsx
- src/pages/Home.page.jsx
- src/pages/province/Banten.province.jsx
- src/pages/province/DkiJakarta.province.jsx
- src/pages/province/JawaBarat.province.jsx
- src/pages/province/JawaTengah.province.jsx
- src/pages/province/JawaTimur.province.jsx
- src/pages/province/Yogjakarta.province.jsx
> feat(further routes): add routes for every province

- src/App.jsx
- src/pages/ProvinceDetails.page.jsx
- src/pages/province/Banten.province.jsx
> Province details page implementation #45

- src/components/Welcome.jsx
> fix: fix contrast

- src/components/DetailCard.jsx
- src/data/dataCultures.js
- src/pages/ProvinceDetails.page.jsx
> feat(display all data culture to card): display all data culture to card

- src/components/FilterCultureButtons.jsx
- src/data/dataCultures.js
- src/pages/ProvinceDetails.page.jsx
> feat(filter cultures): filter cultures by category :)

- src/components/DetailCard.jsx
- src/components/FilterCultureButtons.jsx
- src/pages/ProvinceDetails.page.jsx
> feat: do some modifications

- src/components/AccordionAbout.jsx
- src/components/AccordionItem.jsx
- src/components/DetailCard.jsx
- src/components/FilterCultureButtons.jsx
- src/components/Welcome.jsx
> feat: change background of components to white

- src/data/dataCultures.js
> feat(insert images data to 4 provinces): isert images data

- src/components/ModalProvince.jsx
> feat: make modal close button sticky
